[build]
target = "aarch64-unknown-none"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "target-feature=+crt-static",
    "-C", "relocation-model=static",
]

[target.aarch64-unknown-none]
linker = "aarch64-linux-gnu-ld"
ar = "aarch64-linux-gnu-ar"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
