// SPDX-License-Identifier: MPL-2.0

#pragma once

#define SYS_read        0
#define SYS_write       1
#define SYS_open        2
#define SYS_close       3
#define SYS_stat        4
#define SYS_fstat       5
#define SYS_lseek       8
#define SYS_mmap        9
#define SYS_munmap      11
#define SYS_brk         12
#define SYS_ioctl       16
#define SYS_pipe        22
#define SYS_select      23
#define SYS_dup         32
#define SYS_dup2        33
#define SYS_nanosleep   35
#define SYS_echo        42
#define SYS_socket      41
#define SYS_bind        49
#define SYS_listen      50
#define SYS_accept      51
#define SYS_fork        57
#define SYS_execve      59
#define SYS_exit        60
#define SYS_wait4       61
#define SYS_waitpid     61
#define SYS_kill        62
#define SYS_sigaction   13
#define SYS_sigprocmask 14
#define SYS_ftruncate   77
#define SYS_getcwd      79
#define SYS_chdir       80
#define SYS_flock       73
#define SYS_unlink      87
#define SYS_connect     53
#define SYS_sendto      44
#define SYS_recvfrom    45
#define SYS_mkdir       83
#define SYS_rmdir       84
#define SYS_getdents64  217
#define SYS_getpid      39
#define SYS_openat      257
#define SYS_time_millis 400
